package com.beyondsignal.game.event;
import java.util.*;
public final class ExplorationEventResolver{
 public ExplorationEvent resolve(ExplorationEvent e,ExplorationChoice c,long seed){ Objects.requireNonNull(e); Objects.requireNonNull(c); Random r=new Random(seed^e.id().hashCode()^c.ordinal()); ExplorationOutcome o=outcome(e.type(),c,r); ExplorationEventStatus s=c==ExplorationChoice.IGNORE?ExplorationEventStatus.IGNORED:(o.scoreDelta()<0||o.hullDelta()<=-25?ExplorationEventStatus.FAILED:ExplorationEventStatus.RESOLVED); return e.resolve(c,s,o);}
 private static ExplorationOutcome outcome(ExplorationEventType t,ExplorationChoice c,Random r){ return switch(t){
 case SPATIAL_ANOMALY->switch(c){case INVESTIGATE->chance(r,new ExplorationOutcome(250,0,0,20,"The anomaly yields valuable scientific data."),new ExplorationOutcome(50,0,-12,0,"The ship is damaged by a subspace surge.")); case EVADE->new ExplorationOutcome(20,0,0,0,"The ship safely clears the distortion."); case IGNORE->new ExplorationOutcome(0,0,0,0,"The anomaly is left unexplored."); default->bad(c);};
 case DISTRESS_CALL->switch(c){case ASSIST->chance(r,new ExplorationOutcome(300,8,0,10,"The civilian crew is rescued."),new ExplorationOutcome(100,3,-8,0,"The rescue succeeds, but the ship takes damage.")); case HAIL->new ExplorationOutcome(75,2,0,0,"The distress call is authenticated."); case IGNORE->new ExplorationOutcome(-100,-6,0,0,"The distress call goes unanswered."); default->bad(c);};
 case HOSTILE_AMBUSH->switch(c){case ENGAGE->chance(r,new ExplorationOutcome(400,2,-10,15,"The hostile vessel is driven off."),new ExplorationOutcome(-50,0,-30,0,"The enemy gains the advantage.")); case EVADE->new ExplorationOutcome(50,0,-3,0,"The ship escapes after evasive maneuvers."); case HAIL->chance(r,new ExplorationOutcome(200,6,0,0,"The hostile captain agrees to stand down."),new ExplorationOutcome(-25,-2,-15,0,"Negotiations fail and weapons fire follows.")); default->bad(c);};
 case DERELICT_VESSEL->switch(c){case INVESTIGATE->chance(r,new ExplorationOutcome(180,1,0,25,"The away team recovers logs and supplies."),new ExplorationOutcome(40,0,-10,5,"A dormant defense system activates.")); case SALVAGE->new ExplorationOutcome(80,-2,0,40,"Useful components are recovered."); case IGNORE->new ExplorationOutcome(0,0,0,0,"The derelict remains adrift."); default->bad(c);};
 case DIPLOMATIC_CONTACT->switch(c){case HAIL->chance(r,new ExplorationOutcome(350,10,0,0,"A productive first-contact exchange begins."),new ExplorationOutcome(25,-1,0,0,"The exchange ends in mutual suspicion.")); case EVADE->new ExplorationOutcome(10,-1,0,0,"The unknown vessel is avoided."); case IGNORE->new ExplorationOutcome(-20,-2,0,0,"The contact departs without response."); default->bad(c);};};}
 private static ExplorationOutcome chance(Random r,ExplorationOutcome a,ExplorationOutcome b){return r.nextDouble()<.7?a:b;} private static ExplorationOutcome bad(ExplorationChoice c){throw new IllegalArgumentException("Unsupported choice: "+c);}
}
