package com.beyondsignal.game.combat.event;

public enum CombatEventType {
    TARGET_SELECTED,
    WEAPON_CHARGED,
    WEAPON_FIRED,
    WEAPON_HIT,
    WEAPON_MISSED,
    BEAM_FIRED,
    BEAM_HIT,
    PROJECTILE_CREATED,
    PROJECTILE_EXPIRED,
    PROJECTILE_IMPACT,
    SHIELD_IMPACT,
    SHIELD_COLLAPSED,
    ARMOR_HIT,
    HULL_DAMAGE,
    CRITICAL_HIT,
    SUBSYSTEM_DAMAGED,
    SHIP_DESTROYED
}
